#!/bin/bash


# Define the domain name you want to block
domain="${2}"

# Define the time to block the domain
time="${3}"

# Start the atd service
sudo systemctl start atd

# Add the domain entry to /etc/hosts
if [[ "${1}" = "block" ]]
then
	# Add the domain entry to /etc/hosts
	echo "127.0.0.1   $domain" | sudo tee -a /etc/hosts
	echo "::1         $domain" | sudo tee -a /etc/hosts

	# Restart NetworkManager
	echo "Restarting NetworkManager..."
	sudo systemctl restart NetworkManager

	# Wait for 4 seconds
	sleep 4
	
	# Filepath 
	Filepath="/etc/hosts"

	# Lock the hosts file
	echo "Locking the hosts file..."
	sudo chmod 000 $Filepath
	sudo chattr +i $Filepath  # Set the immutable attribute
	
	
	# Schedule the unlocking using 'at' command
   	echo "sudo chattr -i $Filepath && sudo chmod 644 $Filepath" | at -M now + $time minutes
	
fi

# Remove the domain entry from /etc/hosts
if [[ "${1}" = "unblock" ]]
then
	sed -i "/$domain/d" /etc/hosts
	if [ $? -ne 0 ]; then
    		echo "Error persmission failed , wait till unlocking time."
   		exit 1
	fi
	sudo systemctl restart NetworkManager
	
	sleep 4
	
	sudo systemctl stop atd
	echo "Domain $domain is now accessible"
fi


exit 0
